const API_URL = localStorage.getItem('skylark-api-url') || 'http://localhost:8000';
const app = document.querySelector('#app');
let messages = [];
let loading = false;

const icon = (name) => ({ plus: '＋', refresh: '↻', settings: '⚙', send: '↑', chart: '↗', database: '◫', spark: '✦' }[name]);
const escapeHTML = (value) => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]));
function markdown(text) {
  let html = escapeHTML(text).replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/(^|\n)(\|.+\|\n\|[-:| ]+\|\n(?:\|.+\|\n?)*)/g, (_, start, table) => {
    const rows = table.trim().split('\n').filter((_, index) => index !== 1).map(row => row.split('|').slice(1, -1).map(cell => cell.trim()));
    const header = rows.shift().map(cell => `<th>${cell}</th>`).join('');
    const body = rows.map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('');
    return `${start}<div class="table-wrap"><table><thead><tr>${header}</tr></thead><tbody>${body}</tbody></table></div>`;
  });
  html = html.replace(/^[-•]\s+(.+)$/gm, '<li>$1</li>').replace(/(<li>.*<\/li>)/gs, '<ul>$1</ul>');
  return html.split(/\n{2,}/).map(part => part.startsWith('<ul>') || part.includes('<div class="table-wrap">') ? part : `<p>${part.replace(/\n/g, '<br>')}</p>`).join('');
}
function renderHome() {
  document.title = 'Skylark Intelligence';
  app.innerHTML = `<main class="home"><nav class="home-nav"><div class="brand"><span class="brand-mark">✦</span>Skylark</div><div class="nav-links"><span>Business intelligence</span><span>Monday.com connected</span><button class="button primary" id="go-chat">Open your workspace →</button></div></nav><section class="hero"><div><div class="eyebrow"><i class="pulse"></i> Your data, made clear</div><h1>Turn business data into your next <em>great decision.</em></h1><p>Skylark connects the dots between your sales pipeline and operations. Ask a question in plain language and receive an executive-ready answer in seconds.</p><div class="hero-actions"><button class="button primary" id="hero-chat">Start asking questions →</button><span class="note">Powered by your Monday.com boards</span></div></div><div class="preview"><div class="window"><div class="window-bar"><i></i><i></i><i></i></div><div class="preview-content"><div class="preview-question">Which sectors need my attention this month?</div><div class="preview-answer"><div class="mini-logo"></div><div class="preview-lines"><b>Sector performance overview</b><span></span><span></span></div></div><div class="metrics"><div class="metric"><small>PIPELINE</small><b>₹24.8M</b></div><div class="metric"><small>COLLECTED</small><b class="green">₹12.6M</b></div><div class="metric"><small>AT RISK</small><b>3 sectors</b></div></div></div></div><div class="float-card"><b>Live source context</b>Deals & Work Orders, refreshed automatically.</div></div></section><section class="features"><article class="feature"><div class="feature-icon">${icon('chart')}</div><h3>See the full picture</h3><p>Compare pipeline, delivery, billing, and collection performance across every sector.</p></article><article class="feature"><div class="feature-icon">${icon('spark')}</div><h3>Ask naturally</h3><p>Get direct answers, focused recommendations, and data caveats without wrestling with spreadsheets.</p></article><article class="feature"><div class="feature-icon">${icon('database')}</div><h3>Grounded in your data</h3><p>Every answer cites its data sources and works directly from your connected Monday.com boards.</p></article></section></main>`;
  document.querySelector('#go-chat').onclick = document.querySelector('#hero-chat').onclick = () => { location.hash = '#chat'; render(); };
}
function currentChatHTML() {
  if (!messages.length) return `<div class="welcome"><div class="welcome-logo">✦</div><h1>Good morning. What would you like to know?</h1><p>I can analyze your Deals and Work Orders boards, spot opportunities, and prepare leadership-ready updates.</p><div class="suggestions"><button class="suggestion" data-q="Give me a leadership update"><strong>Leadership update</strong>Summarize sales, operations, billing, and key risks.</button><button class="suggestion" data-q="What is our pipeline by sector?"><strong>Pipeline by sector</strong>See where our strongest opportunities are.</button><button class="suggestion" data-q="Which sectors need attention?"><strong>Sector health</strong>Compare pipeline strength with operational execution.</button><button class="suggestion" data-q="What is our billing and collections status?"><strong>Billing & collections</strong>Understand billed value, collections, and outstanding amounts.</button></div></div>`;
  return messages.map(m => `<article class="message"><div class="avatar ${m.role === 'assistant' ? 'assistant-avatar' : 'user-avatar'}">${m.role === 'assistant' ? '✦' : 'You'}</div><div class="message-body"><div class="message-name">${m.role === 'assistant' ? 'Skylark' : 'You'}</div><div class="message-content">${m.typing ? '<div class="typing"><i></i><i></i><i></i></div>' : markdown(m.content)}</div>${m.meta ? `<div class="message-meta">${m.meta.sources.map(x => `<span class="chip">${escapeHTML(x.replace('Monday.com — ','').replace('Monday.com â€” ',''))}</span>`).join('')}${m.meta.quality.map(x => `<span class="chip quality">${escapeHTML(x)}</span>`).join('')}</div>` : ''}</div></article>`).join('');
}
function renderChat() {
  document.title = 'Skylark · Workspace';
  app.innerHTML = `<div class="chat"><aside class="sidebar"><div class="brand"><span class="brand-mark">✦</span>Skylark</div><button class="new-chat" id="new-chat">${icon('plus')} New conversation</button><div class="history-label">RECENT</div><div id="history">${messages.length ? '<div class="history-item active">Current analysis</div>' : '<div class="history-item">No conversations yet</div>'}</div><div class="sidebar-footer"><span class="status-dot"></span><span id="connection">Checking connection…</span></div></aside><main class="chat-main"><header class="chat-header"><div class="chat-title">Skylark Intelligence <span>Business analyst</span></div><div class="header-actions"><button class="icon-button" id="refresh" title="Refresh Monday.com data">${icon('refresh')}</button><button class="icon-button" id="settings" title="API settings">${icon('settings')}</button></div></header><section class="messages" id="messages">${currentChatHTML()}</section><footer class="composer-wrap"><form class="composer" id="chat-form"><textarea id="prompt" rows="1" placeholder="Ask about your business data…" autofocus></textarea><button class="send" id="send" type="submit" ${loading ? 'disabled' : ''}>${icon('send')}</button></form><div class="disclaimer">Skylark uses your Monday.com Deals and Work Orders data to answer.</div></footer></main></div>`;
  const box = document.querySelector('#messages'); box.scrollTop = box.scrollHeight;
  document.querySelectorAll('[data-q]').forEach(el => el.onclick = () => send(el.dataset.q));
  document.querySelector('#chat-form').onsubmit = e => { e.preventDefault(); send(document.querySelector('#prompt').value); };
  document.querySelector('#new-chat').onclick = () => { messages = []; renderChat(); };
  document.querySelector('#refresh').onclick = refreshData;
  document.querySelector('#settings').onclick = configureApi;
  checkHealth();
}
async function checkHealth() { const target = document.querySelector('#connection'); try { const r = await fetch(`${API_URL}/api/health`); const d = await r.json(); if(target) target.textContent = d.status === 'healthy' ? 'Monday.com connected' : 'Configuration needed'; } catch { if(target) target.textContent = 'Backend unavailable'; } }
async function refreshData() { const button = document.querySelector('#refresh'); button.textContent = '…'; try { const r = await fetch(`${API_URL}/api/refresh`, { method:'POST' }); if (!r.ok) throw new Error(); alert('Your Monday.com data has been refreshed.'); } catch { alert('Unable to refresh data. Check that the backend is running and configured.'); } finally { button.textContent = icon('refresh'); checkHealth(); } }
function configureApi() { const value = prompt('Skylark API URL', API_URL); if(value) { localStorage.setItem('skylark-api-url', value.replace(/\/$/,'')); location.reload(); } }
async function send(question) { question = question.trim(); if (!question || loading) return; messages.push({ role:'user', content:question }); messages.push({ role:'assistant', content:'', typing:true }); loading = true; renderChat(); try { const r = await fetch(`${API_URL}/api/chat`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({message:question, conversation_id:'web-session'}) }); const data = await r.json(); if (!r.ok) throw new Error(data.detail || 'Request failed'); messages[messages.length - 1] = { role:'assistant', content:data.answer, meta:{ sources:data.data_sources || [], quality:data.data_quality || [] } }; } catch (error) { messages[messages.length - 1] = { role:'assistant', content:`**I couldn't complete that request.** ${error.message || 'Please check that the Skylark backend is running and try again.'}` }; } finally { loading = false; renderChat(); } }
function render() { location.hash === '#chat' ? renderChat() : renderHome(); }
window.addEventListener('hashchange', render); render();
